# Generated by Django 5.2.4 on 2025-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('student_class', models.SmallIntegerField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('paid_till_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
