# Generated by Django 5.2.4 on 2025-07-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='quarterly', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'student_class')},
        ),
    ]
