# Generated by Django 5.2.4 on 2025-07-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='quarterly', max_length=20),
        ),
    ]
